from typing import Optional
from pydantic import BaseModel
from typing import List

class LineItem(BaseModel):
    product_id: int
    quantity: int
    price: float


class Order(BaseModel):
    order_id: int = None  # Optional, generated by the system
    customer_id: int
    line_items: List[LineItem]
    total_amount: float = 0.0
    status: str = "PENDING"  # Example: PENDING, PROCESSING, SHIPPED, COMPLETED
